# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad85c17fa6143b43b84a3f974491f2c70be3cd514810ebca21cc18282cfccc11213054c3768a232f2e4d98ffab5cd4c95cf6ae6868d1be1de74b3685a6a75dd5

test:
  secret_key_base: 3d0c20942838b6e8488662e684fe1d50e293af6853ae7d097db208866e6e10703087ea69ac4e92af0efaf840ad83afe4993d03e940ec1ace8e4db6aedaf9b4ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
